### ISSUE TITLE
a problem ?

### ISSUE THREAD

**Issue by AinzOoalGown-fun** [miahela/Discord-Image-Downloader#1]
hello, I launched the program, no image is downloaded. it remains that
node index.js
Started refreshing 1 application (/) commands.
Successfully reloaded 1 application (/) commands.
Logged in as mytok#3880!

Thank you -_-

**Comment by miahela** [comment]
Hello @AinzOoalGown-fun,

I'd like to clarify that I haven't encountered any issues with the bot on my end. However, I'm really keen on helping you resolve this issue you're experiencing.

To start with, could you please provide some more details? Specifically, I'm interested in:

The operating system you're using to host the bot.
Whether you've invited the bot to your server.
Whether you've attempted to use the /extract command.
Please note, the program doesn't download images immediately upon launch. You need to call it using the /extract command as mentioned. The statement you provided, "I launched the program, no image is downloaded," seems to suggest that you might not have taken this step.

Looking forward to your reply so we can get to the bottom of this.

**Comment by AinzOoalGown-fun** [comment]
Hello@miahela
 Thank you for answering me and for wanting to help me.
The bot is created from https://discord.com/developers/applications/ .
yes I invited my bot on my server (not on the server where I want to download images).
I can't run the /extract command because I can't write anything after Connected as mytok#3880!

**Comment by AinzOoalGown-fun** [comment]
https://github.com/miahela/Discord-Image-Downloader/assets/73220716/9ff090da-0073-4a04-b03b-37e9afd253e2

**Comment by miahela** [comment]
Hello @AinzOoalGown-fun,

I appreciate your response and the details you've provided. I will create a video tutorial explaining how to use the bot later for further clarification.

However, I'd like to point out a couple of things here:

1. The bot needs to be invited to the same server where you plan to download images. This is crucial, as the bot won't be able to execute commands or interact in a server it's not a part of.

2. The `/extract` command should be run in the Discord channel from where you want to download the images. It's not something you input into the console where you start the bot server with `node index.js`.

These steps should help you get the bot to download images as expected. Let me know if you have further questions!
